services:
  mariadb-server:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

  mariadb-client:
    image: pontusc/mariadb-python:latest
    command: sleep infinity
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
